### ISSUE TITLE
OAuth authentication flows

### ISSUE THREAD

**Issue by heiko-braun** [agentgateway/agentgateway#152]
What are your thoughts on the oauth flows that made into the MCP spec lately? 

https://modelcontextprotocol.io/specification/2025-06-18/basic/authorization

Does it fit the use cases you have in mind for the gateway?

I guess this would mean the gateway  would somehow be able to allow clients to discover the protected resource metadata as described in  _2.3.2 Server Metadata Discovery_ of the spec?

**Comment by howardjohn** [comment]
I am hoping to do a deep dive into this in the coming weeks - TBD. But definitely something we should address with agentgateway!

**Comment by heiko-braun** [comment]
@howardjohn  with great interest I saw the latest "route" addition to the gateway – well done!
It make a lot of sense and solves the "namespacing" problem with MCP quite nicely. 

I wonder how this impacts the anticipated protected resource metadata setup? Will this evolve in a direction where users are able to configure protected resource metadata per route? This would allow us to line up servers that should be attached to the same auth server behind a single route.

**Comment by howardjohn** [comment]
So at minimum now you could make a route that matches `/.well-known/oauth-protected-resource` and returns a direct response.

Now that I think of it, https://github.com/agentgateway/agentgateway/issues/189 is likely an issue there since we would want to return `content-type: json`, so that would be a small blocker.

We do now have basic support for some specific auth providers (auth0 and keycloak) but should add a generic one https://github.com/agentgateway/agentgateway/issues/190.

The problem I see currently is there are ~zero IDPs that support all the required oauth RFCs to implement the MCP spec. So that leaves the gateway to bridge some of the gaps for them.

I'd love to know what your ideal end state here would look like, if you have one in mind?

**Comment by heiko-braun** [comment]
> I'd love to know what your ideal end state here would look like, if you have one in mind?

Good question. Essentially we want to use the gateway with spec compliant clients (`2025-06-18`), specifically for getting auth solved. There are numerous problems across the board, the least of them reside with the agent gateway. Two main ones for me:

- Have auth working with Keycloak end-to-end (Hinges on https://github.com/keycloak/keycloak/issues/40923)
- Clarify how protected resource metadata from backend servers will represented in agent gateway (federated servers may or may not share the same auth server -> this ticket)

**Comment by howardjohn** [comment]
So we did recently add some experiments around Keycloak, specifically to serve that missing endpoint in agentgateway itself to workaround the gaps in keycloak. Docs are very lacking though

**Comment by heiko-braun** [comment]
Any pointers I can look at? So far I have only seen the latest blog from @christian-posta around this

**Comment by howardjohn** [comment]
```yaml
    routes:
    - name: mcp
      policies:
        backendTLS: {}
        cors:
          allowOrigins:
          - "*"
          allowHeaders:
          - mcp-protocol-version
          - content-type
        timeout:
          requestTimeout: 1500ms
        # Keycloak example. Run `docker compose -f keycloak.yaml up`
        mcpAuthentication:
          issuer: http://localhost:7080/realms/mcp
          scopes: ["profile"]
          audience: http://lo # Does nothing :-(
          provider:
            keycloak: {}
      backends:
      - mcp:
          name: mcp
          targets:
          - name: mcp
            mcp:
              host: ...
```

with

```
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: ["start-dev", "--import-realm", "--http-port", "7080", "--https-port", "7443"]
    volumes:
    - ./mcp-realm.json:/opt/keycloak/data/import/mcp-realm.json
    ports:
    - "7080:7080"
    - "7443:7443"
```
